### ISSUE TITLE
Installation: Adafruit_PWMServoDriver missing

### ISSUE THREAD

**Issue by heuer** [PeterDHabermehl/ftduino_direct#1]
I am using OS X 10.11.x and I followed the install instructions.

If I try to upload the ```ftduino_direct.ino``` I get the following error msg:

```
ftduino_direct:10:37: error: Adafruit_PWMServoDriver.h: No such file or directory
compilation terminated.
exit status 1
Adafruit_PWMServoDriver.h: No such file or directory
```

The installation section does not mention that the "Adafruit PCA9685 PWM Servo Driver Library" is needed. Probably it would be nice to mention that the driver is needed and how install it or do I miss something?

**Comment by heuer** [comment]
I found the solution.

Sketch -> Include Library -> Manage Library

Search for "adafruit servo" -> Install "Adafruit PWM Servo Driver Library"

Maybe this could be mentioned in the docs or is it too obvious? For me, at least, it wasn't ;)

**Comment by PeterDHabermehl** [comment]
Obviously I deemed that to be too obvious. Added a note in the readme. Thanks for bringing it to my attention.
